spring:
  datasource:
    url: jdbc:postgresql://127.0.0.2:5432/APPLICATION
    username: namtv
    password: namtv
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: security
        ddl-auto: create
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect